"""Stock data endpoints generated from ftshare-doc."""

from __future__ import annotations

from .types import Endpoint, build_endpoints


ENDPOINTS: dict[str, Endpoint] = build_endpoints({
    'abnormal_trading_details': {
        'path': 'api/v1/market/data/abnormal-trading-details',
        'title': '龙虎榜明细',
        'doc_file': '龙虎榜明细.md',
        'original_api': 'abnormal_trading_details',
        'params': ('date',),
    },
    'abnormal_trading_overview': {
        'path': 'api/v1/market/data/abnormal-trading-overview',
        'title': '龙虎榜总览',
        'doc_file': '龙虎榜总览.md',
        'original_api': 'abnormal_trading_overview',
        'params': ('date',),
    },
    'auction_results': {
        'path': 'api/v1/market/data/auction-results',
        'title': '集合竞价结果',
        'doc_file': '集合竞价结果.md',
        'original_api': 'auction_results',
        'params': ('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'balance': {
        'path': 'api/v1/market/data/finance/balance',
        'title': 'A股资产负债表',
        'doc_file': 'A股资产负债表.md',
        'original_api': 'balance',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'block_trades': {
        'path': 'api/v1/market/data/block-trades',
        'title': '大宗交易',
        'doc_file': '大宗交易.md',
        'original_api': 'block_trades',
        'params': ('date',),
    },
    'bse_mapping': {
        'path': 'api/v1/market/data/bse-mapping',
        'title': '北交所映射',
        'doc_file': '北交所映射.md',
        'original_api': 'get_bse_mapping',
        'params': ('o_code', 'n_code'),
    },
    'cashflow': {
        'path': 'api/v1/market/data/finance/cashflow',
        'title': 'A股现金流量表',
        'doc_file': 'A股现金流量表.md',
        'original_api': 'cashflow',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'cashflow_stock_code': {
        'path': 'api/v1/market/data/finance/cashflow-stock-code',
        'title': '现金流支持股票代码',
        'doc_file': '现金流支持股票代码.md',
        'original_api': 'get_cashflow_stock_code',
    },
    'company_list': {
        'path': 'api/v1/market/data/company-list',
        'title': '公司列表',
        'doc_file': '公司列表.md',
        'original_api': 'get_company_list',
        'params': ('stock_name', 'stock_code', 'page', 'page_size'),
    },
    'earnings_reports_paginated': {
        'path': 'api/v1/market/data/finance/stock-performance-express',
        'title': '业绩快报',
        'doc_file': '业绩快报.md',
        'original_api': 'earnings_reports_paginated',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'eastmoney_board_constituents': {
        'path': 'api/v1/market/data/eastmoney-board-constituents',
        'title': '东方财富板块成份股',
        'doc_file': '东方财富板块成份股.md',
        'original_api': 'eastmoney_board_constituents',
        'params': ('board_code',),
    },
    'eastmoney_board_daily_kline': {
        'path': 'api/v1/market/data/eastmoney-board-daily-ohlc',
        'title': '东方财富板块日线OHLC',
        'doc_file': '东方财富板块日线OHLC.md',
        'original_api': 'eastmoney_board_daily_kline',
        'params': ('board_code', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_board_latest_kline': {
        'path': 'api/v1/market/data/eastmoney-board-latest-ohlc',
        'title': '东方财富板块最新OHLC',
        'doc_file': '东方财富板块最新OHLC.md',
        'original_api': 'eastmoney_board_latest_kline',
        'params': ('board_code', 'page', 'page_size'),
    },
    'eastmoney_concept_boards': {
        'path': 'api/v1/market/data/eastmoney-concept-boards',
        'title': '东方财富概念板块',
        'doc_file': '东方财富概念板块.md',
        'original_api': 'eastmoney_concept_boards',
    },
    'eastmoney_dapan_flow': {
        'path': 'api/v1/market/data/eastmoney-dapan-flow',
        'title': '东方财富大盘资金流',
        'doc_file': '东方财富大盘资金流.md',
        'original_api': 'get_eastmoney_dapan_flow',
        'params': ('trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_market_valuation': {
        'path': 'api/v1/market/data/eastmoney-market-valuation',
        'title': '东方财富市场估值',
        'doc_file': '东方财富市场估值.md',
        'original_api': 'get_eastmoney_market_valuation',
        'params': ('market_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_rank': {
        'path': 'api/v1/market/data/eastmoney-rank',
        'title': '东方财富股票排名',
        'doc_file': '东方财富股票排名.md',
        'original_api': 'eastmoney_rank',
        'params': ('rank_group', 'market', 'trade_date'),
    },
    'eastmoney_sector_flow': {
        'path': 'api/v1/market/data/eastmoney-sector-flow',
        'title': '东方财富板块资金流',
        'doc_file': '东方财富板块资金流.md',
        'original_api': 'get_eastmoney_sector_flow',
        'params': ('sector_code', 'sector_type', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_stock_flow': {
        'path': 'api/v1/market/data/eastmoney-stock-flow',
        'title': '东方财富个股资金流',
        'doc_file': '东方财富个股资金流.md',
        'original_api': 'get_eastmoney_stock_flow',
        'params': ('symbol', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_stock_valuation': {
        'path': 'api/v1/market/data/eastmoney-stock-valuation',
        'title': '东方财富个股估值',
        'doc_file': '东方财富个股估值.md',
        'original_api': 'get_eastmoney_stock_valuation',
        'params': ('symbol', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'goodwill_industry': {
        'path': 'api/v1/market/data/goodwill/industry',
        'title': '商誉行业',
        'doc_file': '商誉行业.md',
        'original_api': 'goodwill_industry',
        'params': ('date', 'page', 'page_size'),
    },
    'goodwill_market_overview': {
        'path': 'api/v1/market/data/goodwill/market-overview',
        'title': '商誉市场总览',
        'doc_file': '商誉市场总览.md',
        'original_api': 'goodwill_market_overview',
    },
    'goodwill_predict': {
        'path': 'api/v1/market/data/goodwill/predict',
        'title': '商誉预测',
        'doc_file': '商誉预测.md',
        'original_api': 'goodwill_predict',
        'params': ('date', 'page', 'page_size'),
    },
    'goodwill_stock_detail': {
        'path': 'api/v1/market/data/goodwill/stock-detail',
        'title': '商誉个股明细',
        'doc_file': '商誉个股明细.md',
        'original_api': 'goodwill_stock_detail',
        'params': ('date', 'page', 'page_size'),
    },
    'goodwill_stock_impairment': {
        'path': 'api/v1/market/data/goodwill/stock-impairment',
        'title': '商誉减值',
        'doc_file': '商誉减值.md',
        'original_api': 'goodwill_stock_impairment',
        'params': ('date', 'page', 'page_size'),
    },
    'hk_sh_stock_connect_members': {
        'path': 'api/v1/market/data/hk-sh-stock-connect-members',
        'title': '沪港通成份',
        'doc_file': '沪港通成份.md',
        'original_api': 'hk_sh_stock_connect_members',
    },
    'hk_sz_stock_connect_members': {
        'path': 'api/v1/market/data/hk-sz-stock-connect-members',
        'title': '深港通成份',
        'doc_file': '深港通成份.md',
        'original_api': 'hk_sz_stock_connect_members',
    },
    'income': {
        'path': 'api/v1/market/data/finance/income',
        'title': 'A股利润表',
        'doc_file': 'A股利润表.md',
        'original_api': 'income',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'limit_down_pool': {
        'path': 'api/v1/market/data/limit-down-pool',
        'title': '跌停池',
        'doc_file': '跌停池.md',
        'original_api': 'limit_down_pool',
        'params': ('trade_date',),
    },
    'limit_event_timeline_3s': {
        'path': 'api/v1/market/data/limit-event-timeline-3s',
        'title': '涨跌停事件时间线',
        'doc_file': '涨跌停事件时间线.md',
        'original_api': 'limit_event_timeline_3s',
        'params': ('symbol', 'trade_date'),
    },
    'limit_up_break_pool': {
        'path': 'api/v1/market/data/limit-up-break-pool',
        'title': '炸板池',
        'doc_file': '炸板池.md',
        'original_api': 'limit_up_break_pool',
        'params': ('trade_date',),
    },
    'limit_up_pool': {
        'path': 'api/v1/market/data/limit-up-pool',
        'title': '涨停池',
        'doc_file': '涨停池.md',
        'original_api': 'limit_up_pool',
        'params': ('trade_date',),
    },
    'limit_up_pool_yesterday': {
        'path': 'api/v1/market/data/limit-up-pool-yesterday',
        'title': '昨日涨停池',
        'doc_file': '昨日涨停池.md',
        'original_api': 'limit_up_pool_yesterday',
    },
    'margin_trading_details': {
        'path': 'api/v1/market/data/margin-trading-details',
        'title': '融资融券明细',
        'doc_file': '融资融券明细.md',
        'original_api': 'margin_trading_details',
        'params': ('date', 'page', 'page_size'),
    },
    'margin_trading_details_paginated': {
        'path': 'api/v1/market/data/margin-trading-details',
        'title': '融资融券明细分页',
        'doc_file': '融资融券明细分页.md',
        'original_api': 'margin_trading_details_paginated',
        'params': ('date', 'page', 'page_size'),
    },
    'northbound': {
        'path': 'api/v1/market/data/northbound',
        'title': '北向资金交易',
        'doc_file': '北向资金交易.md',
        'original_api': 'northbound',
        'params': ('date',),
    },
    'namechange': {
        'path': 'api/v1/market/data/namechange',
        'title': '股票曾用名',
        'doc_file': '股票曾用名.md',
        'original_api': 'get_namechange',
        'params': ('trade_code', 'start_date', 'end_date'),
    },
    'nth_trade_date': {
        'path': 'api/v1/market/data/time/get-nth-trade-date',
        'title': '第N个交易日',
        'doc_file': '第N个交易日.md',
        'original_api': 'get_nth_trade_date',
        'params': ('n',),
    },
    'performance_forecasts_paginated': {
        'path': 'api/v1/market/data/finance/stock-performance-forecast',
        'title': '业绩预告',
        'doc_file': '业绩预告.md',
        'original_api': 'performance_forecasts_paginated',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'price_change': {
        'path': 'api/v1/market/data/price/get-price-change',
        'title': '价格变动',
        'doc_file': '价格变动.md',
        'original_api': 'get_price_change',
        'params': ('stock_code', 'base_date', 'n', 'direction'),
    },
    'risk_warning_stock_quotes': {
        'path': 'api/v1/market/data/risk-warning-stocks/quotes',
        'title': '风险警示股行情',
        'doc_file': '风险警示股行情.md',
        'original_api': 'risk_warning_stock_quotes',
        'params': ('date',),
    },
    'risk_warning_stocks': {
        'path': 'api/v1/market/data/risk-warning-stocks',
        'title': '风险警示股',
        'doc_file': '风险警示股.md',
        'original_api': 'risk_warning_stocks',
        'params': ('date',),
    },
    'search': {
        'path': 'api/v1/market/security/search',
        'title': '标的搜索',
        'doc_file': '标的搜索.md',
        'original_api': 'search',
        'params': ('query', 'limit'),
    },
    'sh_hk_stock_connect_members': {
        'path': 'api/v1/market/data/sh-hk-stock-connect-members',
        'title': '沪股通成份',
        'doc_file': '沪股通成份.md',
        'original_api': 'sh_hk_stock_connect_members',
    },
    'southbound': {
        'path': 'api/v1/market/data/southbound',
        'title': '南向资金交易',
        'doc_file': '南向资金交易.md',
        'original_api': 'southbound',
        'params': ('date',),
    },
    'stk_ah_comparison': {
        'path': 'api/v1/market/data/hk/stk-ah-comparison',
        'title': 'AH股对比',
        'doc_file': 'AH股对比.md',
        'original_api': 'get_stk_ah_comparison',
        'params': ('hk_code', 'ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        'max_page_size': 1000,
    },
    'stk_code_change': {
        'path': 'api/v1/market/data/stk-code-change',
        'title': 'A股代码变更',
        'doc_file': 'A股代码变更.md',
        'original_api': 'get_stk_code_change',
        'params': ('trade_code', 'start_date', 'end_date'),
    },
    'stk_limit': {
        'path': 'api/v1/market/data/stk-limit',
        'title': '涨跌停价',
        'doc_file': '涨跌停价.md',
        'original_api': 'stk_limit',
        'params': ('instrument_type', 'symbol', 'symbol_id', 'market_id', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'stk_manager_hold': {
        'path': 'api/v1/market/data/stk-manager-hold',
        'title': '上市公司管理层持股',
        'doc_file': '上市公司管理层持股.md',
        'original_api': 'get_stk_manager_hold',
        'params': ('trade_code', 'end_date'),
    },
    'stk_manager_pay': {
        'path': 'api/v1/market/data/stk-manager-pay',
        'title': '上市公司管理层薪酬',
        'doc_file': '上市公司管理层薪酬.md',
        'original_api': 'get_stk_manager_pay',
        'params': ('trade_code', 'end_date'),
    },
    'stk_managers': {
        'path': 'api/v1/market/data/stk-managers',
        'title': '上市公司管理层',
        'doc_file': '上市公司管理层.md',
        'original_api': 'get_stk_managers',
        'params': ('trade_code', 'candi_date', 'begin_date', 'end_date'),
    },
    'stk_premarket': {
        'path': 'api/v1/market/data/stk-premarket',
        'title': '盘前数据',
        'doc_file': '盘前数据.md',
        'original_api': 'stk_premarket',
        'params': ('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'stk_status_change': {
        'path': 'api/v1/market/data/stk-status-change',
        'title': 'A股状态变更',
        'doc_file': 'A股状态变更.md',
        'original_api': 'get_stk_status_change',
        'params': ('trade_code', 'change_date', 'change_type'),
    },
    'stock_adjust_factor': {
        'path': 'api/v1/market/data/stock-adjust-factor',
        'title': '股票复权因子',
        'doc_file': '股票复权因子.md',
        'original_api': 'stock_adjust_factor',
        'params': ('symbol', 'trade_date', 'start_date', 'end_date', 'offset', 'limit'),
    },
    'stock_candlesticks': {
        'path': 'api/v1/market/data/stock-candlesticks',
        'title': '股票K线',
        'doc_file': '股票K线.md',
        'original_api': 'stock_candlesticks',
        'method': 'POST',
        'params': ('symbol', 'interval_unit', 'interval_value', 'adjust_kind', 'since_ts_millis', 'until_ts_millis', 'limit'),
    },
    'stock_candlesticks_batch': {
        'path': 'api/v1/market/data/stock-candlesticks/batch',
        'title': '批量股票K线',
        'doc_file': '批量股票K线.md',
        'original_api': 'stock_candlesticks_batch',
        'method': 'POST',
        'params': ('symbols', 'interval_unit', 'interval_value', 'adjust_kind', 'since_ts_millis', 'until_ts_millis', 'limit'),
    },
    'stock_capital_flows_paginated': {
        'path': 'api/v1/market/data/stock-capital-flows',
        'title': '股票资金流向',
        'doc_file': '股票资金流向.md',
        'original_api': 'stock_capital_flows_paginated',
        'params': ('date', 'page', 'page_size'),
    },
    'stock_comment_desire_em': {
        'path': 'api/v1/market/data/stock-comment/desire',
        'title': '千股千评意愿度',
        'doc_file': '千股千评意愿度.md',
        'original_api': 'stock_comment_desire_em',
        'params': ('symbol',),
    },
    'stock_comment_em': {
        'path': 'api/v1/market/data/stock-comment/index',
        'title': '千股千评',
        'doc_file': '千股千评.md',
        'original_api': 'stock_comment_em',
        'params': ('page', 'page_size'),
    },
    'stock_comment_focus_em': {
        'path': 'api/v1/market/data/stock-comment/focus',
        'title': '千股千评关注度',
        'doc_file': '千股千评关注度.md',
        'original_api': 'stock_comment_focus_em',
        'params': ('symbol',),
    },
    'stock_comment_org_participate_em': {
        'path': 'api/v1/market/data/stock-comment/org-participate',
        'title': '机构参与度',
        'doc_file': '机构参与度.md',
        'original_api': 'stock_comment_org_participate_em',
        'params': ('symbol',),
    },
    'stock_comment_score_em': {
        'path': 'api/v1/market/data/stock-comment/score',
        'title': '千股千评评分',
        'doc_file': '千股千评评分.md',
        'original_api': 'stock_comment_score_em',
        'params': ('symbol',),
    },
    'stock_filter': {
        'path': 'api/v1/market/data/stock-list/filter',
        'title': '股票筛选',
        'doc_file': '股票筛选.md',
        'original_api': 'get_stock_filter',
        'params': ('symbol', 'board', 'listing_date_since', 'page', 'page_size'),
    },
    'stock_float_holders': {
        'path': 'api/v1/market/data/holder/stock-holder-ften',
        'title': '十大流通股东',
        'doc_file': '十大流通股东.md',
        'original_api': 'get_stock_holder_float_top10',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_ggcg_em': {
        'path': 'api/v1/market/data/holder/stock-ggcg-em',
        'title': '东方财富股东增减持',
        'doc_file': '东方财富股东增减持.md',
        'original_api': 'stock_ggcg_em_handler',
        'params': ('symbol', 'page', 'page_size'),
    },
    'stock_ggmx': {
        'path': 'api/v1/market/data/holder/stock-ggmx',
        'title': '董监高持股变动',
        'doc_file': '董监高持股变动.md',
        'original_api': 'stock_ggmx_handler',
        'params': ('stock_code', 'change_direction', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'stock_ggmx_buy_ranking': {
        'path': 'api/v1/market/data/holder/stock-ggmx-buy-ranking',
        'title': '董监高增持排名',
        'doc_file': '董监高增持排名.md',
        'original_api': 'stock_ggmx_buy_ranking_handler',
        'params': ('time_range', 'page', 'page_size'),
    },
    'stock_ggmx_sell_ranking': {
        'path': 'api/v1/market/data/holder/stock-ggmx-sell-ranking',
        'title': '董监高减持排名',
        'doc_file': '董监高减持排名.md',
        'original_api': 'stock_ggmx_sell_ranking_handler',
        'params': ('time_range', 'page', 'page_size'),
    },
    'stock_holders': {
        'path': 'api/v1/market/data/holder/stock-holder-ten',
        'title': '十大股东',
        'doc_file': '十大股东.md',
        'original_api': 'get_stock_holder_top10',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_holders_number': {
        'path': 'api/v1/market/data/holder/stock-holder-nums',
        'title': '股东人数',
        'doc_file': '股东人数.md',
        'original_api': 'get_stock_holder_nums',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_institution_holdings': {
        'path': 'api/v1/market/data/share/stock-institution-holdings',
        'title': '机构持股',
        'doc_file': '机构持股.md',
        'original_api': 'get_stock_institution_holdings',
        'params': ('year', 'report_type', 'inst_type', 'page', 'page_size'),
    },
    'stock_institution_holdings_detail': {
        'path': 'api/v1/market/data/share/stock-institution-holdings-detail',
        'title': '机构持股明细',
        'doc_file': '机构持股明细.md',
        'original_api': 'get_stock_institution_holdings_detail',
        'params': ('stock_code', 'year', 'report_type', 'inst_type', 'page', 'page_size'),
    },
    'stock_institution_share_holdings': {
        'path': 'api/v1/market/data/institution/institution-share-holdings',
        'title': '机构股本持股',
        'doc_file': '机构股本持股.md',
        'original_api': 'get_stock_institution_share_holdings',
        'params': ('institution_id', 'year', 'report_type', 'invest_type'),
    },
    'stock_intraday_auction_volume': {
        'path': 'api/v1/market/data/intraday-auction-volume',
        'title': '集合竞价成交量',
        'doc_file': '集合竞价成交量.md',
        'original_api': 'stock_intraday_auction_volume',
        'params': ('trade_date', 'page', 'page_size'),
    },
    'stock_intraday_auction_volume_symbol': {
        'path': 'api/v1/market/data/intraday-auction-volume/symbol',
        'title': '单标的集合竞价成交量',
        'doc_file': '单标的集合竞价成交量.md',
        'original_api': 'stock_intraday_auction_volume_symbol',
        'params': ('symbol', 'trade_date', 'page', 'page_size'),
    },
    'stock_ipos': {
        'path': 'api/v1/market/data/stock-ipos',
        'title': '股票IPO',
        'doc_file': '股票IPO.md',
        'original_api': 'stock_ipos',
        'params': ('page', 'page_size'),
    },
    'stock_list': {
        'path': 'api/v1/market/data/stock-list',
        'title': '股票列表',
        'doc_file': '股票列表.md',
        'original_api': 'get_stock_list',
    },
    'stock_market': {
        'path': 'api/v1/market/data/daec/market/snapshot',
        'title': '市场行情快照',
        'doc_file': '市场行情快照.md',
        'original_api': 'stock_market',
        'params': ('scope',),
    },
    'stock_market_distribution_intraday': {
        'path': 'api/v1/market/data/daec/market/distribution-history',
        'title': '日内涨跌停分布历史',
        'doc_file': '日内涨跌停分布历史.md',
        'original_api': 'stock_market_distribution_intraday',
        'params': ('scope',),
    },
    'stock_daec_stocks': {
        'path': 'api/v1/market/data/daec/stocks/{board}',
        'title': 'A股行情列表',
        'doc_file': 'A股行情列表.md',
        'original_api': 'stock_daec_stocks',
        'params': ('board', 'page', 'page_size', 'filter', 'order_by'),
        'path_params': ('board',),
    },
    'stock_realtime_list': {
        'path': 'api/v1/market/data/stock-list/{board}',
        'title': 'A股行情列表',
        'doc_file': 'A股行情列表.md',
        'original_api': 'stock_realtime_list',
        'params': ('board', 'page', 'page_size'),
        'path_params': ('board',),
    },
    'stock_pledge_detail': {
        'path': 'api/v1/market/data/pledge/pledge-detail',
        'title': '股权质押明细',
        'doc_file': '股权质押明细.md',
        'original_api': 'stock_pledge_detail',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_pledge_summary': {
        'path': 'api/v1/market/data/pledge/pledge-summary',
        'title': '股权质押汇总',
        'doc_file': '股权质押汇总.md',
        'original_api': 'stock_pledge_summary',
        'params': ('page', 'page_size'),
    },
    'stock_prev_close': {
        'path': 'api/v1/market/data/daec/history/prev-closes',
        'title': '标的昨收价',
        'doc_file': '标的昨收价.md',
        'original_api': 'stock_prev_close',
        'params': ('symbol', 'since', 'until'),
    },
    'stock_intraday_prices': {
        'path': 'api/v1/market/data/daec/history/prices',
        'title': '标的分时数据',
        'doc_file': '标得分时数据.md',
        'original_api': 'stock_intraday_prices',
        'params': ('symbol', 'range', 'days', 'ts_ms', 'compat', 'since', 'since_ts_ms'),
    },
    'stock_ohlcs': {
        'path': 'api/v1/market/data/daec/history/ohlcs',
        'title': '标的K线数据',
        'doc_file': '标的K线数据.md',
        'original_api': 'stock_ohlcs',
        'params': ('symbol', 'since', 'until', 'interval', 'adjust', 'compat', 'span', 'limit', 'until_ts_ms'),
    },
    'stock_rating_top5': {
        'path': 'api/v1/market/data/feitu/stock-rating-top5',
        'title': '飞兔股票评级Top5',
        'doc_file': '飞兔股票评级Top5.md',
        'original_api': 'stock_rating_top5',
        'params': ('date', 'variant', 'type'),
    },
    'stock_share': {
        'path': 'api/v1/market/data/share/get-stock-share',
        'title': '股本',
        'doc_file': '股本.md',
        'original_api': 'get_stock_share',
        'params': ('stock_code', 'date'),
    },
    'stock_share_chg': {
        'path': 'api/v1/market/data/holder/stock-share-chg',
        'title': '股东增减持',
        'doc_file': '股东增减持.md',
        'original_api': 'get_stock_share_chg',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_signal_latest_snapshot': {
        'path': 'api/v1/market/data/stock-signal-latest-snapshot',
        'title': '信号最新快照',
        'doc_file': '信号最新快照.md',
        'original_api': 'stock_signal_latest_snapshot',
        'params': ('signal_type', 'page', 'page_size'),
    },
    'stock_unlock': {
        'path': 'api/v1/market/data/unlock/stock-unlock',
        'title': '限售解禁',
        'doc_file': '限售解禁.md',
        'original_api': 'stock_unlock_handler',
        'params': ('stock_code', 'page', 'page_size'),
    },
    'stock_unlock_by_date': {
        'path': 'api/v1/market/data/unlock/stock-unlock-by-date',
        'title': '限售解禁按日期',
        'doc_file': '限售解禁按日期.md',
        'original_api': 'stock_unlock_by_date_handler',
        'params': ('start_date', 'end_date', 'page', 'page_size'),
    },
    'suspension_list': {
        'path': 'api/v1/market/data/suspension-list',
        'title': '停牌列表',
        'doc_file': '停牌列表.md',
        'original_api': 'suspension_list',
        'params': ('trade_date', 'page', 'page_size'),
    },
    'sz_hk_stock_connect_members': {
        'path': 'api/v1/market/data/sz-hk-stock-connect-members',
        'title': '深股通成份',
        'doc_file': '深股通成份.md',
        'original_api': 'sz_hk_stock_connect_members',
    },
    'ths_all_board_kline': {
        'path': 'api/v1/market/data/ths-all-board-kline',
        'title': '同花顺全板块K线',
        'doc_file': '同花顺全板块K线.md',
        'original_api': 'ths_all_board_kline',
        'params': ('start_date', 'end_date', 'page', 'page_size'),
    },
    'ths_board_kline': {
        'path': 'api/v1/market/data/ths-board-kline',
        'title': '同花顺板块K线',
        'doc_file': '同花顺板块K线.md',
        'original_api': 'ths_board_kline',
        'params': ('board_code', 'page', 'page_size'),
    },
    'ths_board_list': {
        'path': 'api/v1/market/data/ths-board-list',
        'title': '同花顺板块列表',
        'doc_file': '同花顺板块列表.md',
        'original_api': 'ths_board_list',
    },
    'xueqiu_rank': {
        'path': 'api/v1/market/data/xueqiu-rank',
        'title': '雪球股票排名',
        'doc_file': '雪球股票排名.md',
        'original_api': 'xueqiu_rank',
        'params': ('rank_group', 'period', 'trade_date', 'page', 'page_size'),
        'max_page_size': 100,
    },
    'yzxdr_detail': {
        'path': 'api/v1/market/data/yzxdr-detail',
        'title': '除权除息明细',
        'doc_file': '除权除息明细.md',
        'original_api': 'get_yzxdr_detail',
        'params': ('year', 'quarter', 'stock_code', 'page', 'page_size'),
    },
    'pledge_summary': {
        'path': 'api/v1/market/data/pledge/pledge-summary',
        'title': '股权质押汇总',
        'doc_file': '股权质押汇总.md',
        'original_api': 'stock_pledge_summary',
        'params': ('page', 'page_size'),
    },
    'stock_capital_flows': {
        'path': 'api/v1/market/data/stock-capital-flows',
        'title': '股票资金流向',
        'doc_file': '股票资金流向.md',
        'original_api': 'stock_capital_flows_paginated',
        'params': ('date', 'page', 'page_size'),
    },
})
