"""Stock data endpoints generated from ftshare-doc."""

from __future__ import annotations

from .types import Endpoint, build_endpoints


ENDPOINTS: dict[str, Endpoint] = build_endpoints({
    'abnormal_trading_details': {
        'path': 'api/v1/market/data/abnormal-trading-details',
        'title': '龙虎榜明细',
        'doc_file': '龙虎榜明细.md',
        'original_api': 'abnormal_trading_details',
        'params': ('date', 'page', 'page_size'),
    },
    'abnormal_trading_overview': {
        'path': 'api/v1/market/data/abnormal-trading-overview',
        'title': '龙虎榜总览',
        'doc_file': '龙虎榜总览.md',
        'original_api': 'abnormal_trading_overview',
        'params': ('date', 'page', 'page_size'),
    },
    'auction_results': {
        'path': 'api/v2/market/data/auction-results',
        'title': '集合竞价结果',
        'doc_file': '集合竞价结果.md',
        'original_api': 'auction_results',
        'params': ('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'balance': {
        'path': 'api/v1/market/data/finance/balance',
        'title': 'A股资产负债表',
        'doc_file': 'A股资产负债表.md',
        'original_api': 'balance',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'block_trades': {
        'path': 'api/v1/market/data/block-trades',
        'title': '大宗交易',
        'doc_file': '大宗交易.md',
        'original_api': 'block_trades',
        'params': ('date', 'page', 'page_size'),
    },
    'bse_mapping': {
        'path': 'api/v1/market/data/bse-mapping',
        'title': '北交所映射',
        'doc_file': '北交所映射.md',
        'original_api': 'get_bse_mapping',
        'params': ('o_code', 'n_code'),
    },
    'cashflow': {
        'path': 'api/v1/market/data/finance/cashflow',
        'title': 'A股现金流量表',
        'doc_file': 'A股现金流量表.md',
        'original_api': 'cashflow',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'cashflow_stock_code': {
        'path': 'api/v2/market/data/finance/cashflow-stock-code',
        'title': '现金流支持股票代码',
        'doc_file': '现金流支持股票代码.md',
        'original_api': 'get_cashflow_stock_code',
    },
    'company_list': {
        'path': 'api/v1/market/data/company-list',
        'title': '公司列表',
        'doc_file': '公司列表.md',
        'original_api': 'get_company_list',
        'params': ('stock_name', 'stock_code', 'page', 'page_size'),
    },
    'earnings_reports_paginated': {
        'path': 'api/v1/market/data/finance/stock-performance-express',
        'title': '业绩快报',
        'doc_file': '业绩快报.md',
        'original_api': 'earnings_reports_paginated',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'eastmoney_board_constituents': {
        'path': 'api/v2/market/data/eastmoney-board-constituents',
        'title': '东方财富板块成份股',
        'doc_file': '东方财富板块成份股.md',
        'original_api': 'eastmoney_board_constituents',
        'params': ('board_code',),
    },
    'eastmoney_board_daily_kline': {
        'path': 'api/v2/market/data/eastmoney-board-daily-ohlc',
        'title': '东方财富板块日线OHLC',
        'doc_file': '东方财富板块日线OHLC.md',
        'original_api': 'eastmoney_board_daily_kline',
        'params': ('board_code', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_concept_boards': {
        'path': 'api/v2/market/data/eastmoney-concept-boards',
        'title': '东方财富概念板块',
        'doc_file': '东方财富概念板块.md',
        'original_api': 'eastmoney_concept_boards',
    },
    'eastmoney_dapan_flow': {
        'path': 'api/v2/market/data/eastmoney-dapan-flow',
        'title': '东方财富大盘资金流',
        'doc_file': '东方财富大盘资金流.md',
        'original_api': 'get_eastmoney_dapan_flow',
        'params': ('trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_market_valuation': {
        'path': 'api/v1/market/data/eastmoney-market-valuation',
        'title': '东方财富市场估值',
        'doc_file': '东方财富市场估值.md',
        'original_api': 'get_eastmoney_market_valuation',
        'params': ('market_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_rank': {
        'path': 'api/v2/market/data/eastmoney-rank',
        'title': '东方财富股票排名',
        'doc_file': '东方财富股票排名.md',
        'original_api': 'eastmoney_rank',
        'params': ('rank_group', 'market', 'trade_date'),
    },
    'eastmoney_sector_flow': {
        'path': 'api/v2/market/data/eastmoney-sector-flow',
        'title': '东方财富板块资金流',
        'doc_file': '东方财富板块资金流.md',
        'original_api': 'get_eastmoney_sector_flow',
        'params': ('sector_code', 'sector_type', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_stock_flow': {
        'path': 'api/v1/market/data/eastmoney-stock-flow',
        'title': '东方财富个股资金流',
        'doc_file': '东方财富个股资金流.md',
        'original_api': 'get_eastmoney_stock_flow',
        'params': ('symbol', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'eastmoney_stock_valuation': {
        'path': 'api/v1/market/data/eastmoney-stock-valuation',
        'title': '东方财富个股估值',
        'doc_file': '东方财富个股估值.md',
        'original_api': 'get_eastmoney_stock_valuation',
        'params': ('symbol', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'goodwill_industry': {
        'path': 'api/v1/market/data/goodwill/industry',
        'title': '商誉行业',
        'doc_file': '商誉行业.md',
        'original_api': 'goodwill_industry',
        'params': ('date', 'page', 'page_size'),
    },
    'goodwill_market_overview': {
        'path': 'api/v1/market/data/goodwill/market-overview',
        'title': '商誉市场总览',
        'doc_file': '商誉市场总览.md',
        'original_api': 'goodwill_market_overview',
    },
    'goodwill_predict': {
        'path': 'api/v1/market/data/goodwill/predict',
        'title': '商誉预测',
        'doc_file': '商誉预测.md',
        'original_api': 'goodwill_predict',
        'params': ('date', 'page', 'page_size'),
    },
    'goodwill_stock_detail': {
        'path': 'api/v1/market/data/goodwill/stock-detail',
        'title': '商誉个股明细',
        'doc_file': '商誉个股明细.md',
        'original_api': 'goodwill_stock_detail',
        'params': ('date', 'page', 'page_size'),
    },
    'goodwill_stock_impairment': {
        'path': 'api/v1/market/data/goodwill/stock-impairment',
        'title': '商誉减值',
        'doc_file': '商誉减值.md',
        'original_api': 'goodwill_stock_impairment',
        'params': ('date', 'page', 'page_size'),
    },
    'income': {
        'path': 'api/v1/market/data/finance/income',
        'title': 'A股利润表',
        'doc_file': 'A股利润表.md',
        'original_api': 'income',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'limit_event_timeline_3s': {
        'path': 'api/v2/market/data/limit-event-timeline-3s',
        'title': '涨跌停事件时间线',
        'doc_file': '涨跌停事件时间线.md',
        'original_api': 'limit_event_timeline_3s',
        'params': ('symbol', 'trade_date'),
    },
    'limit_up_briefs': {
        'path': 'api/v3/market/data/limit-up-reports/briefs',
        'title': '涨停简报',
        'doc_file': '涨停简报.md',
        'original_api': 'limit_up_briefs',
        'params': ('date',),
    },
    'margin_trading_details': {
        'path': 'api/v1/market/data/margin-trading-details',
        'title': '融资融券明细',
        'doc_file': '融资融券明细.md',
        'original_api': 'margin_trading_details',
        'params': ('date', 'page', 'page_size'),
    },
    'northbound': {
        'path': 'api/v1/market/data/northbound',
        'title': '北向资金交易',
        'doc_file': '北向资金交易.md',
        'original_api': 'northbound',
        'params': ('date',),
    },
    'namechange': {
        'path': 'api/v1/market/data/namechange',
        'title': '股票曾用名',
        'doc_file': '股票曾用名.md',
        'original_api': 'get_namechange',
        'params': ('trade_code', 'start_date', 'end_date'),
    },
    'trading_calendar': {
        'path': 'api/v1/market/data/time/trading-calendar',
        'title': '交易日历',
        'doc_file': '交易日历.md',
        'original_api': 'trading_calendar',
        'params': ('market', 'start_date', 'end_date'),
    },
    'performance_forecasts_paginated': {
        'path': 'api/v1/market/data/finance/stock-performance-forecast',
        'title': '业绩预告',
        'doc_file': '业绩预告.md',
        'original_api': 'performance_forecasts_paginated',
        'params': ('stock_code', 'year', 'report_type', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'price_change': {
        'path': 'api/v2/market/data/price/get-price-change',
        'title': '价格变动',
        'doc_file': '价格变动.md',
        'original_api': 'get_price_change',
        'params': ('stock_code', 'base_date', 'n', 'direction'),
    },
    'risk_warning_stock_quotes': {
        'path': 'api/v2/market/data/risk-warning-stocks/quotes',
        'title': '风险警示股行情',
        'doc_file': '风险警示股行情.md',
        'original_api': 'risk_warning_stock_quotes',
        'params': ('date',),
    },
    'risk_warning_stocks': {
        'path': 'api/v1/market/data/risk-warning-stocks',
        'title': '风险警示股',
        'doc_file': '风险警示股.md',
        'original_api': 'risk_warning_stocks',
        'params': ('date', 'page', 'page_size'),
    },
    'search': {
        'path': 'api/v2/market/security/search/',
        'title': '标的搜索',
        'doc_file': '标的搜索.md',
        'original_api': 'search',
        'params': ('query', 'limit'),
    },
    'southbound': {
        'path': 'api/v1/market/data/southbound',
        'title': '南向资金交易',
        'doc_file': '南向资金交易.md',
        'original_api': 'southbound',
        'params': ('date',),
    },
    'stk_limit': {
        'path': 'api/v1/market/data/stk-limit',
        'title': '涨跌停价',
        'doc_file': '涨跌停价.md',
        'original_api': 'stk_limit',
        'params': ('instrument_type', 'symbol', 'symbol_id', 'market_id', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'stk_manager_hold': {
        'path': 'api/v1/market/data/stk-manager-hold',
        'title': '上市公司管理层持股',
        'doc_file': '上市公司管理层持股.md',
        'original_api': 'get_stk_manager_hold',
        'params': ('trade_code', 'end_date'),
    },
    'stk_manager_pay': {
        'path': 'api/v1/market/data/stk-manager-pay',
        'title': '上市公司管理层薪酬',
        'doc_file': '上市公司管理层薪酬.md',
        'original_api': 'get_stk_manager_pay',
        'params': ('trade_code', 'end_date'),
    },
    'stk_managers': {
        'path': 'api/v1/market/data/stk-managers',
        'title': '上市公司管理层',
        'doc_file': '上市公司管理层.md',
        'original_api': 'get_stk_managers',
        'params': ('trade_code', 'candi_date', 'begin_date', 'end_date'),
    },
    'stk_premarket': {
        'path': 'api/v2/market/data/stk-premarket',
        'title': '盘前数据',
        'doc_file': '盘前数据.md',
        'original_api': 'stk_premarket',
        'params': ('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        'max_page_size': 500,
    },
    'stock_adjust_factor': {
        'path': 'api/v1/market/data/stock-adjust-factor',
        'title': '股票复权因子',
        'doc_file': '股票复权因子.md',
        'original_api': 'stock_adjust_factor',
        'params': ('symbol', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'stock_candlesticks': {
        'path': 'api/v1/market/data/stock-candlesticks',
        'title': '股票K线',
        'doc_file': '股票K线.md',
        'original_api': 'stock_candlesticks',
        'method': 'GET',
        'params': ('symbol', 'interval_unit', 'interval_value', 'adjust_kind', 'since_ts_millis', 'until_ts_millis', 'limit'),
    },
    'stock_capital_flows': {
        'path': 'api/v1/market/data/stock-capital-flows',
        'title': '股票资金流向',
        'doc_file': '股票资金流向.md',
        'original_api': 'stock_capital_flows_paginated',
        'params': ('date', 'time', 'symbol', 'page', 'page_size'),
    },
    'stock_comment_desire_em': {
        'path': 'api/v1/market/data/stock-comment/desire',
        'title': '千股千评意愿度',
        'doc_file': '千股千评意愿度.md',
        'original_api': 'stock_comment_desire_em',
        'params': ('symbol',),
    },
    'stock_comment_em': {
        'path': 'api/v1/market/data/stock-comment/index',
        'title': '千股千评',
        'doc_file': '千股千评.md',
        'original_api': 'stock_comment_em',
        'params': ('page', 'page_size'),
    },
    'stock_comment_focus_em': {
        'path': 'api/v1/market/data/stock-comment/focus',
        'title': '千股千评关注度',
        'doc_file': '千股千评关注度.md',
        'original_api': 'stock_comment_focus_em',
        'params': ('symbol',),
    },
    'stock_comment_org_participate_em': {
        'path': 'api/v1/market/data/stock-comment/org-participate',
        'title': '机构参与度',
        'doc_file': '机构参与度.md',
        'original_api': 'stock_comment_org_participate_em',
        'params': ('symbol',),
    },
    'stock_comment_score_em': {
        'path': 'api/v1/market/data/stock-comment/score',
        'title': '千股千评评分',
        'doc_file': '千股千评评分.md',
        'original_api': 'stock_comment_score_em',
        'params': ('symbol',),
    },
    'stock_filter': {
        'path': 'api/v2/market/data/stock-list/filter',
        'title': '股票筛选',
        'doc_file': '股票筛选.md',
        'original_api': 'get_stock_filter',
        'params': ('symbol', 'board', 'listing_date_since', 'page', 'page_size'),
    },
    'stock_float_holders': {
        'path': 'api/v1/market/data/holder/stock-holder-ften',
        'title': '十大流通股东',
        'doc_file': '十大流通股东.md',
        'original_api': 'get_stock_holder_float_top10',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_ggmx_buy_ranking': {
        'path': 'api/v3/market/data/holder/stock-ggmx-buy-ranking',
        'title': '董监高增持排名',
        'doc_file': '董监高增持排名.md',
        'original_api': 'stock_ggmx_buy_ranking_handler',
        'params': ('time_range', 'page', 'page_size'),
    },
    'stock_ggmx_sell_ranking': {
        'path': 'api/v3/market/data/holder/stock-ggmx-sell-ranking',
        'title': '董监高减持排名',
        'doc_file': '董监高减持排名.md',
        'original_api': 'stock_ggmx_sell_ranking_handler',
        'params': ('time_range', 'page', 'page_size'),
    },
    'stock_holders': {
        'path': 'api/v1/market/data/holder/stock-holder-ten',
        'title': '十大股东',
        'doc_file': '十大股东.md',
        'original_api': 'get_stock_holder_top10',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_holders_number': {
        'path': 'api/v1/market/data/holder/stock-holder-nums',
        'title': '股东人数',
        'doc_file': '股东人数.md',
        'original_api': 'get_stock_holder_nums',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_institution_holdings': {
        'path': 'api/v3/market/data/share/stock-institution-holdings',
        'title': '机构持股',
        'doc_file': '机构持股.md',
        'original_api': 'get_stock_institution_holdings',
        'params': ('year', 'report_type', 'institution_type', 'page', 'page_size'),
    },
    'stock_institution_holdings_detail': {
        'path': 'api/v3/market/data/share/stock-institution-holdings-detail',
        'title': '机构持股明细',
        'doc_file': '机构持股明细.md',
        'original_api': 'get_stock_institution_holdings_detail',
        'params': ('stock_code', 'year', 'report_type', 'institution_type', 'page', 'page_size'),
    },
    'stock_institution_share_holdings': {
        'path': 'api/v3/market/data/institution/institution-share-holdings',
        'title': '机构股本持股',
        'doc_file': '机构股本持股.md',
        'original_api': 'get_stock_institution_share_holdings',
        'params': ('institution_id', 'year', 'report_type', 'invest_type'),
    },
    'stock_intraday_auction_volume': {
        'path': 'api/v2/market/data/intraday-auction-volume',
        'title': '连续竞价成交量',
        'doc_file': '连续竞价成交量.md',
        'original_api': 'stock_intraday_auction_volume',
        'params': ('trade_date', 'page', 'page_size'),
    },
    'stock_ipos': {
        'path': 'api/v1/market/data/stock-ipos',
        'title': '股票IPO',
        'doc_file': '股票IPO.md',
        'original_api': 'stock_ipos',
        'params': ('page', 'page_size'),
    },
    'stock_list': {
        'path': 'api/v1/market/data/stock-list',
        'title': '股票列表',
        'doc_file': '股票列表.md',
        'original_api': 'get_stock_list',
        'params': ('page', 'page_size'),
    },
    'stock_market': {
        'path': 'api/v1/market/data/daec/market/snapshot',
        'title': '市场行情快照',
        'doc_file': '市场行情快照.md',
        'original_api': 'stock_market',
        'params': ('scope',),
    },
    'stock_market_distribution_intraday': {
        'path': 'api/v2/market/data/market-distribution-intraday',
        'title': '市场涨跌分布分时',
        'doc_file': '市场涨跌分布分时.md',
        'original_api': 'stock_market_distribution_intraday',
        'params': (),
    },
    'stock_daec_stocks': {
        'path': 'api/v1/market/data/daec/stocks/{board}',
        'title': 'A股行情列表',
        'doc_file': 'A股行情列表.md',
        'original_api': 'stock_daec_stocks',
        'params': ('board', 'page', 'page_size', 'filter', 'order_by'),
        'path_params': ('board',),
    },
    'stock_realtime_list': {
        'path': 'api/v1/market/data/stock-list/{board}',
        'title': 'A股行情列表',
        'doc_file': 'A股行情列表.md',
        'original_api': 'stock_realtime_list',
        'params': ('board', 'page', 'page_size'),
        'path_params': ('board',),
    },
    'stock_pledge_detail': {
        'path': 'api/v1/market/data/pledge/pledge-detail',
        'title': '股权质押明细',
        'doc_file': '股权质押明细.md',
        'original_api': 'stock_pledge_detail',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'pledge_summary': {
        'path': 'api/v1/market/data/pledge/pledge-summary',
        'title': '股权质押汇总',
        'doc_file': '股权质押汇总.md',
        'original_api': 'stock_pledge_summary',
        'params': ('page', 'page_size'),
    },
    'stock_prev_close': {
        'path': 'api/v1/market/data/daec/history/prev-closes',
        'title': '标的昨收价',
        'doc_file': '标的昨收价.md',
        'original_api': 'stock_prev_close',
        'params': ('symbol', 'since', 'until'),
    },
    'stock_intraday_prices': {
        'path': 'api/v4/market/data/daec/history/prices',
        'title': '标的分时数据',
        'doc_file': '标的分时数据.md',
        'original_api': 'daec_history_prices',
        'params': ('symbol', 'range', 'days', 'ts_ms'),
    },
    'stock_share': {
        'path': 'api/v2/market/data/share/get-stock-share',
        'title': '股本',
        'doc_file': '股本.md',
        'original_api': 'get_stock_share',
        'params': ('stock_code', 'date'),
    },
    'stock_share_chg': {
        'path': 'api/v1/market/data/holder/stock-share-chg',
        'title': '股东增减持',
        'doc_file': '股东增减持.md',
        'original_api': 'get_stock_share_chg',
        'params': ('stock_code', 'is_last', 'page', 'page_size'),
    },
    'stock_unlock': {
        'path': 'api/v1/market/data/unlock/stock_unlock',
        'title': '限售解禁',
        'doc_file': '限售解禁.md',
        'original_api': 'stock_unlock_handler',
        'params': ('stock_code', 'start_date', 'end_date', 'page', 'page_size'),
    },
    'suspension_list': {
        'path': 'api/v1/market/data/suspension-list',
        'title': '停牌列表',
        'doc_file': '停牌列表.md',
        'original_api': 'suspension_list',
        'params': ('trade_date', 'page', 'page_size'),
    },
    'ths_board_kline': {
        'path': 'api/v2/market/data/ths-board-kline',
        'title': '同花顺板块K线',
        'doc_file': '同花顺板块K线.md',
        'original_api': 'ths_board_kline',
        'params': ('board_code', 'page', 'page_size'),
    },
    'xueqiu_rank': {
        'path': 'api/v2/market/data/xueqiu-rank',
        'title': '雪球股票排名',
        'doc_file': '雪球股票排名.md',
        'original_api': 'xueqiu_rank',
        'params': ('rank_group', 'period', 'trade_date', 'page', 'page_size'),
        'max_page_size': 100,
    },
    'yzxdr_detail': {
        'path': 'api/v1/market/data/yzxdr-detail',
        'title': '一致行动人明细',
        'doc_file': '一致行动人明细.md',
        'original_api': 'get_yzxdr_detail',
        'params': ('year', 'quarter', 'stock_code', 'page', 'page_size'),
    },
    'stock_description_all': {
        'path': 'api/v1/market/data/stock-description-all',
        'title': '股票基础信息',
        'doc_file': '股票基础信息.md',
        'original_api': 'stock_description_all',
    },

    'tdx_board_index': {
        'path': 'api/v1/market/data/tdx-board-index',
        'title': '通达信板块指数最新快照',
        'doc_file': '通达信板块指数最新快照.md',
        'original_api': 'tdx_board_index',
        'params': ('ts_code', 'idx_name', 'idx_type', 'idx_type_code', 'market', 'page', 'page_size'),
    },

    'tdx_board_daily': {
        'path': 'api/v1/market/data/tdx-board-daily',
        'title': '通达信板块日线',
        'doc_file': '通达信板块日线.md',
        'original_api': 'tdx_board_daily',
        'params': ('start_date', 'end_date', 'ts_code', 'idx_name', 'idx_type', 'idx_type_code', 'market', 'page', 'page_size'),
    },

    'tdx_board_members': {
        'path': 'api/v2/market/data/tdx-board-members',
        'title': '通达信板块成分股最新快照',
        'doc_file': '通达信板块成分股最新快照.md',
        'original_api': 'tdx_board_members',
        'params': ('ts_code', 'idx_name', 'idx_type', 'idx_type_code', 'market', 'con_code', 'con_name', 'page', 'page_size'),
    },

    'stock_dividends': {
        'path': 'api/v1/market/data/stock-dividends',
        'title': '股票分红记录',
        'doc_file': '股票分红记录.md',
        'original_api': 'stock_dividends',
        'params': ('symbol', 'since_date', 'until_date', 'page', 'page_size'),
    },

    'stock_history_list': {
        'path': 'api/v1/market/data/stock-history-list',
        'title': '股票历史列表',
        'doc_file': '股票历史列表.md',
        'original_api': 'stock_history_list',
        'params': ('trade_date', 'code', 'page', 'page_size'),
    },

    'stock_connect_members': {
        'path': 'api/v1/market/data/stock-connect-members',
        'title': '互联互通成份',
        'doc_file': '互联互通成份.md',
        'original_api': 'stock_connect_members',
        'params': ('direction', 'channel', 'page', 'page_size'),
    },

    'limit_list': {
        'path': 'api/v1/market/data/limit-list',
        'title': '涨跌停池',
        'doc_file': '涨跌停池.md',
        'original_api': 'limit_list',
        'params': ('limit_type', 'trade_date'),
    },

    'stk_surv': {
        'path': 'api/v2/market/data/stk-surv',
        'title': '个股严重异常波动',
        'doc_file': '个股严重异常波动.md',
        'original_api': 'stk_surv',
        'params': ('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },

    'stk_shock': {
        'path': 'api/v2/market/data/stk-shock',
        'title': '个股异常波动',
        'doc_file': '个股异常波动.md',
        'original_api': 'stk_shock',
        'params': ('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
    },

    'stk_alert_broker': {
        'path': 'api/v2/market/data/stk-alert-broker',
        'title': '交易所重点提示证券',
        'doc_file': '交易所重点提示证券.md',
        'original_api': 'stk_alert_broker',
        'params': ('ts_code', 'start_date', 'end_date', 'page', 'page_size'),
    },

    'limit_up_public_report': {
        'path': 'api/v3/market/data/limit-up-reports/public-report',
        'title': '涨停对外归因报告',
        'doc_file': '涨停对外归因报告.md',
        'original_api': 'limit_up_public_report',
        'params': ('date', 'security_code'),
    },

    'limit_up_briefs': {
        'path': 'api/v3/market/data/limit-up-reports/briefs',
        'title': '涨停简报',
        'doc_file': '涨停简报.md',
        'original_api': 'limit_up_briefs',
        'params': ('date',),
    },

    'ths_hot_list': {
        'path': 'api/v2/market/data/ths-hot-list',
        'title': '同花顺热榜',
        'doc_file': '同花顺热榜.md',
        'original_api': 'ths_hot_list',
        'params': ('list_type', 'trade_date', 'page', 'page_size'),
    },

    'ashare_news_sentiment_factors': {
        'path': 'api/v3/market/data/ashare-news-sentiment-factors',
        'title': 'A股新闻情绪因子',
        'doc_file': 'A股新闻情绪因子.md',
        'original_api': 'ashare_news_sentiment_factors',
        'params': ('trade_code', 'start_date', 'end_date', 'page', 'page_size'),
    },

    'kline_pattern_annotations': {
        'path': 'api/v3/market/data/kline-pattern-annotations',
        'title': 'K线形态标注',
        'doc_file': 'K线形态标注.md',
        'original_api': 'kline_pattern_annotations',
        'params': ('date', 'symbol', 'pattern', 'page', 'page_size'),
    },

    'ashare_interactions': {
        'path': 'api/v3/market/data/ashare-interactions',
        'title': 'e互动',
        'doc_file': 'e互动.md',
        'original_api': 'ashare_interactions',
        'params': ('start_date', 'end_date', 'trade_code', 'company_name', 'industry_code', 'industry_name', 'data_source', 'page', 'page_size'),
    },

    'supply_chain_subindustry_supply_chain': {
        'path': 'api/v3/market/data/supply-chain/subindustry-supply-chain',
        'title': '供应链一跳关系',
        'doc_file': '供应链一跳关系.md',
        'original_api': 'supply_chain_subindustry_supply_chain',
        'params': ('industry_name', 'direction'),
    },

    'supply_chain_company_supply_chain_companies': {
        'path': 'api/v3/market/data/supply-chain/company-supply-chain-companies',
        'title': '供应链公司候选',
        'doc_file': '供应链公司候选.md',
        'original_api': 'supply_chain_company_supply_chain_companies',
        'params': ('trade_code', 'direction', 'page', 'page_size'),
    },

    'supply_chain_subsubindustry_companies': {
        'path': 'api/v3/market/data/supply-chain/subsubindustry-companies',
        'title': '供应链子子行业公司映射',
        'doc_file': '供应链子子行业公司映射.md',
        'original_api': 'supply_chain_subsubindustry_companies',
        'params': ('subindustry_name',),
    },

    'supply_chain_subsubindustry_parent_subindustries': {
        'path': 'api/v3/market/data/supply-chain/subsubindustry-parent-subindustries',
        'title': '供应链子子行业父行业反查',
        'doc_file': '供应链子子行业父行业反查.md',
        'original_api': 'supply_chain_subsubindustry_parent_subindustries',
        'params': ('subindustry_name',),
    },

    'supply_chain_subindustry_subsubindustries': {
        'path': 'api/v3/market/data/supply-chain/subindustry-subsubindustries',
        'title': '供应链子行业层级展开',
        'doc_file': '供应链子行业层级展开.md',
        'original_api': 'supply_chain_subindustry_subsubindustries',
        'params': ('industry_name',),
    },

    'exchange_margin_summaries': {
        'path': 'api/v1/market/data/exchange-margin-summaries',
        'title': '交易所融资融券汇总日度',
        'doc_file': '交易所融资融券汇总日度.md',
        'original_api': 'exchange_margin_summaries',
        'params': ('start_date', 'end_date', 'exchange', 'page', 'page_size'),
        'max_page_size': 1000,
    },

    'ashare_rating_factor_snapshot': {
        'path': 'api/v3/market/data/ashare-rating-factor-snapshot',
        'title': 'A股相关性 Top-K',
        'doc_file': 'A股相关性Top-K.md',
        'original_api': 'ashare_rating_factor_snapshot',
        'params': ('trade_code', 'date', 'top_k'),
    },

    'stock_minutes': {
        'path': 'api/v3/market/data/stock_minutes',
        'title': '股票历史分钟行情',
        'doc_file': '股票历史分钟行情.md',
        'original_api': 'stock_minutes',
        'params': ('symbol', 'interval_value', 'adjust_kind', 'since_ts_millis', 'until_ts_millis', 'limit'),
    },

    'stock_realtime_minute_kline': {
        'path': 'api/v4/market/data/stock-realtime-minute-kline',
        'title': '股票实时分钟K线',
        'doc_file': '股票实时分钟K线.md',
        'original_api': 'stock_realtime_minute_kline',
        'params': ('symbols',),
    },

    'stock_realtime_day_kline': {
        'path': 'api/v4/market/data/stock-realtime-day-kline',
        'title': '股票实时日K线',
        'doc_file': '股票实时日K线.md',
        'original_api': 'stock_realtime_day_kline',
        'params': ('symbols',),
    },

})
